/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.example;

import java.time.LocalDate;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.example.controller.FuncionarioController;
import org.example.dominio.Funcionario;

/**
 *
 * @author Simon
 */
public class Main2 extends javax.swing.JFrame {

    private final FuncionarioController funcionarioController;
    private final String[] COLUMNAS = {"CEDULA","TIPO_CEDULA","NOMBRE","APELLIDOS","ESTADO_CIVIL",
    "SEXO","DIRECCION","TELEFONO","FECHA_NACIMIENTO"};
    private final String SELECCIONAR = "-- SELECCIONAR --";
    /**
     * Creates new form Main2
     */
    public Main2() {
        initComponents();
        funcionarioController = new FuncionarioController();
        textFieldCedulaEdit.setEditable(false);
        listarFuncionarios();
        addListener();
    }

    private void listarFuncionarios() {
        jComboBoxFuncionarios.removeAllItems();
        
        Funcionario funcionario = new Funcionario();
        funcionario.setNombre(SELECCIONAR);
        funcionario.setId(0);
        jComboBoxFuncionarios.addItem(funcionario);
        
        
        DefaultTableModel defaultTableModel = new DefaultTableModel();
        
        
        
        List<Funcionario> funcionarios = funcionarioController.showFuncionarios();
        
        if(funcionarios.isEmpty()){
            JOptionPane.showMessageDialog(null, "No hay funcionarios para mostrar :(","Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        for(String columna : COLUMNAS){
          defaultTableModel.addColumn(columna);
        }
        
        jTableFuncionarios.setModel(defaultTableModel);
        
        defaultTableModel.setRowCount(funcionarios.size());
        
        
        for(int i=0;i< funcionarios.size(); i++ ){
            defaultTableModel.setValueAt(funcionarios.get(i).getId(), i, 0);
            defaultTableModel.setValueAt(funcionarios.get(i).getTipoId(), i, 1);
            defaultTableModel.setValueAt(funcionarios.get(i).getNombre(), i, 2);
            defaultTableModel.setValueAt(funcionarios.get(i).getApellido(), i, 3);
            defaultTableModel.setValueAt(funcionarios.get(i).getEstadoCivil(), i, 4);
            defaultTableModel.setValueAt(funcionarios.get(i).getSexo(), i, 5);
            defaultTableModel.setValueAt(funcionarios.get(i).getDireccion(), i, 6);
            defaultTableModel.setValueAt(funcionarios.get(i).getTelefono(), i, 7);
            defaultTableModel.setValueAt(funcionarios.get(i).getFechaNacimiento(), i, 8);
            jComboBoxFuncionarios.addItem(funcionarios.get(i));
        }
    }
    
    private void addListener(){
        jComboBoxFuncionarios.addItemListener(event -> {
            Funcionario funcionarioSelected = (Funcionario) event.getItem();
            if(funcionarioSelected.toString().equals("0 "+SELECCIONAR)){
                textFieldCedulaEdit.setText("");
                textFieldTipoCedulaEdit.setText("");
                textFieldNombreEdit.setText("");
                textFieldApellidosEdit.setText("");
                textFieldEstadoCivilEdit.setText("");
                textFieldSexoEdit.setText("");
                textFieldDireccion.setText("");
                textFieldTelefono.setText("");
                textFieldFechaNacimientoEdit.setText("");
                return;
            }
            textFieldCedulaEdit.setText(funcionarioSelected.getId().toString());
            textFieldTipoCedulaEdit.setText(funcionarioSelected.getTipoId());
            textFieldNombreEdit.setText(funcionarioSelected.getNombre());
            textFieldApellidosEdit.setText(funcionarioSelected.getApellido());
            textFieldEstadoCivilEdit.setText(funcionarioSelected.getEstadoCivil());
            textFieldSexoEdit.setText(funcionarioSelected.getSexo().toString());
            textFieldDireccionEdit.setText(funcionarioSelected.getDireccion());
            textFieldTelefonoEdit.setText(funcionarioSelected.getTelefono());
            textFieldFechaNacimientoEdit.setText(funcionarioSelected.getFechaNacimiento().toString());
            
            
            
        });
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTPanels = new javax.swing.JTabbedPane();
        jPanelCrearFuncionario = new javax.swing.JPanel();
        jPanelOpciones1 = new javax.swing.JPanel();
        labelCedula = new javax.swing.JLabel();
        labelTipoCedula = new javax.swing.JLabel();
        textFieldCedula = new javax.swing.JTextField();
        labelNombre = new javax.swing.JLabel();
        textFieldTipoCedula = new javax.swing.JTextField();
        textFieldNombre = new javax.swing.JTextField();
        labelApellidos = new javax.swing.JLabel();
        textFieldApellidos = new javax.swing.JTextField();
        labelEstadoCivil = new javax.swing.JLabel();
        textFieldEstadoCivil = new javax.swing.JTextField();
        labelSexo = new javax.swing.JLabel();
        textFieldSexo = new javax.swing.JTextField();
        labelDireccion = new javax.swing.JLabel();
        textFieldDireccion = new javax.swing.JTextField();
        labelTelefono = new javax.swing.JLabel();
        textFieldTelefono = new javax.swing.JTextField();
        labelFechaNacimiento = new javax.swing.JLabel();
        textFieldFechaNacimiento = new javax.swing.JTextField();
        btnCrear = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableFuncionarios = new javax.swing.JTable();
        jPanelEditarFuncionario = new javax.swing.JPanel();
        jPanelOpcionesEdit = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jComboBoxFuncionarios = new javax.swing.JComboBox<>();
        labelCedulaEdit = new javax.swing.JLabel();
        labelTipoCedulaEdit = new javax.swing.JLabel();
        labelNombreEdit = new javax.swing.JLabel();
        labelApellidosEdit = new javax.swing.JLabel();
        labelEstadoCivilEdit = new javax.swing.JLabel();
        labelSexoEdit = new javax.swing.JLabel();
        labelDireccionEdit = new javax.swing.JLabel();
        labelTelefonoEdit = new javax.swing.JLabel();
        labelFechaNacimientoEdit = new javax.swing.JLabel();
        textFieldCedulaEdit = new javax.swing.JTextField();
        textFieldTipoCedulaEdit = new javax.swing.JTextField();
        textFieldNombreEdit = new javax.swing.JTextField();
        textFieldApellidosEdit = new javax.swing.JTextField();
        textFieldEstadoCivilEdit = new javax.swing.JTextField();
        textFieldSexoEdit = new javax.swing.JTextField();
        textFieldDireccionEdit = new javax.swing.JTextField();
        textFieldTelefonoEdit = new javax.swing.JTextField();
        textFieldFechaNacimientoEdit = new javax.swing.JTextField();
        btnActualizar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 51, 204));
        jLabel1.setText("GESTIÓN FUNCIONARIOS");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 10, -1, 20));

        jPanelOpciones1.setBackground(new java.awt.Color(0, 153, 153));
        jPanelOpciones1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Crear un funcionario", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12), new java.awt.Color(0, 255, 204))); // NOI18N

        labelCedula.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelCedula.setText("CEDULA");

        labelTipoCedula.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelTipoCedula.setText("TIPO_CEDULA");

        textFieldCedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldCedulaActionPerformed(evt);
            }
        });

        labelNombre.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelNombre.setText("NOMBRE");

        labelApellidos.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelApellidos.setText("APELLIDOS");

        labelEstadoCivil.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelEstadoCivil.setText("ESTADO_CIVIL");

        textFieldEstadoCivil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldEstadoCivilActionPerformed(evt);
            }
        });

        labelSexo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelSexo.setText("SEXO");

        labelDireccion.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelDireccion.setText("DIRECCION");

        labelTelefono.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelTelefono.setText("TELEFONO");

        labelFechaNacimiento.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelFechaNacimiento.setText("FECHA_NACIMIENTO");

        btnCrear.setBackground(new java.awt.Color(255, 153, 51));
        btnCrear.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCrear.setText("CREAR");
        btnCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelOpciones1Layout = new javax.swing.GroupLayout(jPanelOpciones1);
        jPanelOpciones1.setLayout(jPanelOpciones1Layout);
        jPanelOpciones1Layout.setHorizontalGroup(
            jPanelOpciones1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelOpciones1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelOpciones1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelOpciones1Layout.createSequentialGroup()
                        .addGroup(jPanelOpciones1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textFieldTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelTelefono)
                            .addComponent(textFieldCedula))
                        .addGap(24, 24, 24))
                    .addGroup(jPanelOpciones1Layout.createSequentialGroup()
                        .addComponent(labelCedula)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanelOpciones1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelTipoCedula)
                    .addGroup(jPanelOpciones1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(textFieldTipoCedula)
                        .addComponent(labelFechaNacimiento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(textFieldFechaNacimiento)))
                .addGroup(jPanelOpciones1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelOpciones1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanelOpciones1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelNombre)
                            .addComponent(textFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(jPanelOpciones1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textFieldApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelApellidos))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelOpciones1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelEstadoCivil)
                            .addComponent(textFieldEstadoCivil, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelOpciones1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textFieldSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelSexo))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelOpciones1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textFieldDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelDireccion)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelOpciones1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(btnCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 441, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(76, 76, 76))
        );
        jPanelOpciones1Layout.setVerticalGroup(
            jPanelOpciones1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelOpciones1Layout.createSequentialGroup()
                .addContainerGap(8, Short.MAX_VALUE)
                .addGroup(jPanelOpciones1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCedula)
                    .addComponent(labelTipoCedula)
                    .addComponent(labelNombre)
                    .addComponent(labelApellidos)
                    .addComponent(labelEstadoCivil)
                    .addComponent(labelSexo)
                    .addComponent(labelDireccion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelOpciones1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textFieldCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldTipoCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldEstadoCivil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelOpciones1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTelefono)
                    .addComponent(labelFechaNacimiento))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelOpciones1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCrear)
                    .addGroup(jPanelOpciones1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(textFieldTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(textFieldFechaNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(5, 5, 5))
        );

        jTableFuncionarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane3.setViewportView(jTableFuncionarios);

        javax.swing.GroupLayout jPanelCrearFuncionarioLayout = new javax.swing.GroupLayout(jPanelCrearFuncionario);
        jPanelCrearFuncionario.setLayout(jPanelCrearFuncionarioLayout);
        jPanelCrearFuncionarioLayout.setHorizontalGroup(
            jPanelCrearFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCrearFuncionarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCrearFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane3)
                    .addComponent(jPanelOpciones1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelCrearFuncionarioLayout.setVerticalGroup(
            jPanelCrearFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCrearFuncionarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelOpciones1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTPanels.addTab("Crear funcionario", jPanelCrearFuncionario);

        jPanelOpcionesEdit.setBackground(new java.awt.Color(0, 153, 204));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("FUNCIONARIOS");

        labelCedulaEdit.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelCedulaEdit.setText("CEDULA");

        labelTipoCedulaEdit.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelTipoCedulaEdit.setText("TIPO_CEDULA");

        labelNombreEdit.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelNombreEdit.setText("NOMBRE");

        labelApellidosEdit.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelApellidosEdit.setText("APELLIDOS");

        labelEstadoCivilEdit.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelEstadoCivilEdit.setText("ESTADO_CIVIL");

        labelSexoEdit.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelSexoEdit.setText("SEXO");

        labelDireccionEdit.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelDireccionEdit.setText("DIRECCION");

        labelTelefonoEdit.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelTelefonoEdit.setText("TELEFONO");

        labelFechaNacimientoEdit.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelFechaNacimientoEdit.setText("FECHA_NACIMIENTO");

        btnActualizar.setBackground(new java.awt.Color(255, 255, 51));
        btnActualizar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnActualizar.setText("ACTUALIZAR");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        btnEliminar.setBackground(new java.awt.Color(255, 51, 51));
        btnEliminar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnEliminar.setText("ELIMINAR");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelOpcionesEditLayout = new javax.swing.GroupLayout(jPanelOpcionesEdit);
        jPanelOpcionesEdit.setLayout(jPanelOpcionesEditLayout);
        jPanelOpcionesEditLayout.setHorizontalGroup(
            jPanelOpcionesEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelOpcionesEditLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanelOpcionesEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelOpcionesEditLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBoxFuncionarios, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelOpcionesEditLayout.createSequentialGroup()
                        .addGroup(jPanelOpcionesEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(labelCedulaEdit)
                            .addComponent(labelDireccionEdit)
                            .addComponent(textFieldCedulaEdit, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                            .addComponent(textFieldDireccionEdit))
                        .addGap(29, 29, 29)
                        .addGroup(jPanelOpcionesEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(textFieldTipoCedulaEdit, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)
                            .addComponent(labelTipoCedulaEdit)
                            .addComponent(labelTelefonoEdit)
                            .addComponent(textFieldTelefonoEdit))
                        .addGap(30, 30, 30)
                        .addGroup(jPanelOpcionesEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanelOpcionesEditLayout.createSequentialGroup()
                                .addGroup(jPanelOpcionesEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelNombreEdit)
                                    .addComponent(textFieldNombreEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(23, 23, 23)
                                .addGroup(jPanelOpcionesEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelApellidosEdit)
                                    .addComponent(textFieldApellidosEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(23, 23, 23)
                                .addGroup(jPanelOpcionesEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(labelEstadoCivilEdit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(textFieldEstadoCivilEdit))
                                .addGap(18, 18, 18)
                                .addGroup(jPanelOpcionesEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelSexoEdit)
                                    .addComponent(textFieldSexoEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanelOpcionesEditLayout.createSequentialGroup()
                                .addGroup(jPanelOpcionesEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(textFieldFechaNacimientoEdit, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelFechaNacimientoEdit, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addComponent(btnActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap(153, Short.MAX_VALUE))
        );
        jPanelOpcionesEditLayout.setVerticalGroup(
            jPanelOpcionesEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelOpcionesEditLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanelOpcionesEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBoxFuncionarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jPanelOpcionesEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCedulaEdit)
                    .addComponent(labelTipoCedulaEdit)
                    .addComponent(labelNombreEdit)
                    .addComponent(labelApellidosEdit)
                    .addComponent(labelEstadoCivilEdit)
                    .addComponent(labelSexoEdit))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelOpcionesEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textFieldCedulaEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldTipoCedulaEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldNombreEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldApellidosEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldEstadoCivilEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldSexoEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanelOpcionesEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelDireccionEdit)
                    .addComponent(labelTelefonoEdit)
                    .addComponent(labelFechaNacimientoEdit))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelOpcionesEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textFieldDireccionEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldTelefonoEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldFechaNacimientoEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnActualizar)
                    .addComponent(btnEliminar))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelEditarFuncionarioLayout = new javax.swing.GroupLayout(jPanelEditarFuncionario);
        jPanelEditarFuncionario.setLayout(jPanelEditarFuncionarioLayout);
        jPanelEditarFuncionarioLayout.setHorizontalGroup(
            jPanelEditarFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelOpcionesEdit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelEditarFuncionarioLayout.setVerticalGroup(
            jPanelEditarFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEditarFuncionarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelOpcionesEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(100, Short.MAX_VALUE))
        );

        jTPanels.addTab("Editar Funcionario", jPanelEditarFuncionario);

        getContentPane().add(jTPanels, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 810, 380));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textFieldCedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldCedulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldCedulaActionPerformed

    private void textFieldEstadoCivilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldEstadoCivilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldEstadoCivilActionPerformed

    private void btnCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearActionPerformed
        if(textFieldCedula.getText().trim().length() == 0){
            JOptionPane.showMessageDialog(null,"El campo cédula no debe ser vacío", "Warning", JOptionPane.WARNING_MESSAGE);
            textFieldCedula.requestFocus();
            return;
        }
        if(textFieldTipoCedula.getText().trim().length() == 0){
            JOptionPane.showMessageDialog(null,"El campo tipo cédula no debe ser vacío", "Warning", JOptionPane.WARNING_MESSAGE);
            textFieldTipoCedula.requestFocus();
            return;
        }
        if(textFieldNombre.getText().trim().length() == 0){
            JOptionPane.showMessageDialog(null,"El campo nombre no debe ser vacío", "Warning", JOptionPane.WARNING_MESSAGE);
            textFieldNombre.requestFocus();
            return;
        }
        if(textFieldApellidos.getText().trim().length() == 0){
            JOptionPane.showMessageDialog(null,"El campo apellidos no debe ser vacío", "Warning", JOptionPane.WARNING_MESSAGE);
            textFieldApellidos.requestFocus();
            return;
        }
        if(textFieldEstadoCivil.getText().trim().length() == 0){
            JOptionPane.showMessageDialog(null,"El campo estado civil no debe ser vacío", "Warning", JOptionPane.WARNING_MESSAGE);
            textFieldEstadoCivil.requestFocus();
            return;
        }
        if(textFieldSexo.getText().trim().length() == 0){
            JOptionPane.showMessageDialog(null,"El campo sexo no debe ser vacío", "Warning", JOptionPane.WARNING_MESSAGE);
            textFieldSexo.requestFocus();
            return;
        }
        if(textFieldDireccion.getText().trim().length() == 0){
            JOptionPane.showMessageDialog(null,"El campo direccion no debe ser vacío", "Warning", JOptionPane.WARNING_MESSAGE);
            textFieldDireccion.requestFocus();
            return;
        }
         if(textFieldTelefono.getText().trim().length() == 0){
            JOptionPane.showMessageDialog(null,"El campo telefono no debe ser vacío", "Warning", JOptionPane.WARNING_MESSAGE);
            textFieldTelefono.requestFocus();
            return;
        }
         if(textFieldFechaNacimiento.getText().trim().length() == 0){
            JOptionPane.showMessageDialog(null,"El campo fecha nacimiento no debe ser vacío", "Warning", JOptionPane.WARNING_MESSAGE);
            textFieldFechaNacimiento.requestFocus();
            return;
        }
         Funcionario funcionario = new Funcionario();
         funcionario.setId(Integer.valueOf(textFieldCedula.getText().trim()));
         funcionario.setTipoId(textFieldTipoCedula.getText().trim());
         funcionario.setNombre(textFieldNombre.getText().trim());
         funcionario.setApellido(textFieldApellidos.getText().trim());
         funcionario.setEstadoCivil(textFieldEstadoCivil.getText().trim());
         funcionario.setSexo(textFieldSexo.getText().trim().charAt(0));
         funcionario.setDireccion(textFieldDireccion.getText().trim());
         funcionario.setTelefono(textFieldTelefono.getText().trim());
         funcionario.setFechaNacimiento(LocalDate.parse(textFieldFechaNacimiento.getText().trim()));
         textFieldCedula.setText("");
         textFieldTipoCedula.setText("");
         textFieldNombre.setText("");
         textFieldApellidos.setText("");
         textFieldEstadoCivil.setText("");
         textFieldSexo.setText("");
         textFieldDireccion.setText("");
         textFieldTelefono.setText("");
         textFieldFechaNacimiento.setText("");
         funcionarioController.createFuncionario(funcionario);
         listarFuncionarios();
        
        
        
        
    }//GEN-LAST:event_btnCrearActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
          
        if(textFieldTipoCedulaEdit.getText().trim().length() == 0){
            JOptionPane.showMessageDialog(null,"El campo tipo cédula no debe ser vacío", "Warning", JOptionPane.WARNING_MESSAGE);
            textFieldTipoCedula.requestFocus();
            return;
        }
        if(textFieldNombreEdit.getText().trim().length() == 0){
            JOptionPane.showMessageDialog(null,"El campo nombre no debe ser vacío", "Warning", JOptionPane.WARNING_MESSAGE);
            textFieldNombre.requestFocus();
            return;
        }
        if(textFieldApellidosEdit.getText().trim().length() == 0){
            JOptionPane.showMessageDialog(null,"El campo apellidos no debe ser vacío", "Warning", JOptionPane.WARNING_MESSAGE);
            textFieldApellidos.requestFocus();
            return;
        }
        if(textFieldEstadoCivilEdit.getText().trim().length() == 0){
            JOptionPane.showMessageDialog(null,"El campo estado civil no debe ser vacío", "Warning", JOptionPane.WARNING_MESSAGE);
            textFieldEstadoCivil.requestFocus();
            return;
        }
        if(textFieldSexoEdit.getText().trim().length() == 0){
            JOptionPane.showMessageDialog(null,"El campo sexo no debe ser vacío", "Warning", JOptionPane.WARNING_MESSAGE);
            textFieldSexo.requestFocus();
            return;
        }
        if(textFieldDireccionEdit.getText().trim().length() == 0){
            JOptionPane.showMessageDialog(null,"El campo direccion no debe ser vacío", "Warning", JOptionPane.WARNING_MESSAGE);
            textFieldDireccion.requestFocus();
            return;
        }
         if(textFieldTelefonoEdit.getText().trim().length() == 0){
            JOptionPane.showMessageDialog(null,"El campo telefono no debe ser vacío", "Warning", JOptionPane.WARNING_MESSAGE);
            textFieldTelefono.requestFocus();
            return;
        }
         if(textFieldFechaNacimientoEdit.getText().trim().length() == 0){
            JOptionPane.showMessageDialog(null,"El campo fecha nacimiento no debe ser vacío", "Warning", JOptionPane.WARNING_MESSAGE);
            textFieldFechaNacimiento.requestFocus();
            return;
        }
         Funcionario funcionario = new Funcionario();
         funcionario.setId(Integer.valueOf(textFieldCedulaEdit.getText().trim()));
         funcionario.setTipoId(textFieldTipoCedulaEdit.getText().trim());
         funcionario.setNombre(textFieldNombreEdit.getText().trim());
         funcionario.setApellido(textFieldApellidosEdit.getText().trim());
         funcionario.setEstadoCivil(textFieldEstadoCivilEdit.getText().trim());
         funcionario.setSexo(textFieldSexoEdit.getText().trim().charAt(0));
         funcionario.setDireccion(textFieldDireccionEdit.getText().trim());
         funcionario.setTelefono(textFieldTelefonoEdit.getText().trim());
         funcionario.setFechaNacimiento(LocalDate.parse(textFieldFechaNacimientoEdit.getText().trim()));
         textFieldCedulaEdit.setText("");
         textFieldTipoCedulaEdit.setText("");
         textFieldNombreEdit.setText("");
         textFieldApellidosEdit.setText("");
         textFieldEstadoCivilEdit.setText("");
         textFieldSexoEdit.setText("");
         textFieldDireccionEdit.setText("");
         textFieldTelefonoEdit.setText("");
         textFieldFechaNacimientoEdit.setText("");
         boolean funcionarioFoundAndUpdated = funcionarioController.updateFuncionario(funcionario,funcionario.getId());
         if(!funcionarioFoundAndUpdated){
             JOptionPane.showMessageDialog(null,"No se pudo actualizar al funcionario con ID = "+ textFieldCedulaEdit.getText().trim(), "Warning", JOptionPane.WARNING_MESSAGE );
             return;
         }
         JOptionPane.showMessageDialog(null, "Funcionario actualizado satisfactoriamente", "SUCCESS",JOptionPane.INFORMATION_MESSAGE);
         listarFuncionarios();
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        if(textFieldCedulaEdit.getText().trim().length() == 0){
            JOptionPane.showMessageDialog(null, "Debe seleccionar a un funcionaro", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        Integer idFuncionario = Integer.valueOf(textFieldCedulaEdit.getText().trim());
        boolean funcionarioEliminado = funcionarioController.deleteFuncionario(idFuncionario);
        if(!funcionarioEliminado){
            JOptionPane.showMessageDialog(null, "No se pudo eliminar al usuario con ID = "+ idFuncionario, "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        JOptionPane.showMessageDialog(null,"Usuario eliminado satisfactoriamente!","SUCCESS", JOptionPane.INFORMATION_MESSAGE);
        listarFuncionarios();
        textFieldCedulaEdit.setText("");
         textFieldTipoCedulaEdit.setText("");
         textFieldNombreEdit.setText("");
         textFieldApellidosEdit.setText("");
         textFieldEstadoCivilEdit.setText("");
         textFieldSexoEdit.setText("");
         textFieldDireccionEdit.setText("");
         textFieldTelefonoEdit.setText("");
         textFieldFechaNacimientoEdit.setText("");
    }//GEN-LAST:event_btnEliminarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnCrear;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JComboBox<Funcionario> jComboBoxFuncionarios;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanelCrearFuncionario;
    private javax.swing.JPanel jPanelEditarFuncionario;
    private javax.swing.JPanel jPanelOpciones1;
    private javax.swing.JPanel jPanelOpcionesEdit;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTPanels;
    private javax.swing.JTable jTableFuncionarios;
    private javax.swing.JLabel labelApellidos;
    private javax.swing.JLabel labelApellidosEdit;
    private javax.swing.JLabel labelCedula;
    private javax.swing.JLabel labelCedulaEdit;
    private javax.swing.JLabel labelDireccion;
    private javax.swing.JLabel labelDireccionEdit;
    private javax.swing.JLabel labelEstadoCivil;
    private javax.swing.JLabel labelEstadoCivilEdit;
    private javax.swing.JLabel labelFechaNacimiento;
    private javax.swing.JLabel labelFechaNacimientoEdit;
    private javax.swing.JLabel labelNombre;
    private javax.swing.JLabel labelNombreEdit;
    private javax.swing.JLabel labelSexo;
    private javax.swing.JLabel labelSexoEdit;
    private javax.swing.JLabel labelTelefono;
    private javax.swing.JLabel labelTelefonoEdit;
    private javax.swing.JLabel labelTipoCedula;
    private javax.swing.JLabel labelTipoCedulaEdit;
    private javax.swing.JTextField textFieldApellidos;
    private javax.swing.JTextField textFieldApellidosEdit;
    private javax.swing.JTextField textFieldCedula;
    private javax.swing.JTextField textFieldCedulaEdit;
    private javax.swing.JTextField textFieldDireccion;
    private javax.swing.JTextField textFieldDireccionEdit;
    private javax.swing.JTextField textFieldEstadoCivil;
    private javax.swing.JTextField textFieldEstadoCivilEdit;
    private javax.swing.JTextField textFieldFechaNacimiento;
    private javax.swing.JTextField textFieldFechaNacimientoEdit;
    private javax.swing.JTextField textFieldNombre;
    private javax.swing.JTextField textFieldNombreEdit;
    private javax.swing.JTextField textFieldSexo;
    private javax.swing.JTextField textFieldSexoEdit;
    private javax.swing.JTextField textFieldTelefono;
    private javax.swing.JTextField textFieldTelefonoEdit;
    private javax.swing.JTextField textFieldTipoCedula;
    private javax.swing.JTextField textFieldTipoCedulaEdit;
    // End of variables declaration//GEN-END:variables
}
